# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Initialise <- function(nResolution = 10L) {
    .Call('RasterAnalyser_Initialise', PACKAGE = 'RasterAnalyser', nResolution)
}

Destroy <- function(pRasterImage) {
    .Call('RasterAnalyser_Destroy', PACKAGE = 'RasterAnalyser', pRasterImage)
}

DrawPolygon <- function(pRasterImage, arrayX, arrayY, aLengths) {
    .Call('RasterAnalyser_DrawPolygon', PACKAGE = 'RasterAnalyser', pRasterImage, arrayX, arrayY, aLengths)
}

Intersect <- function(pRasterImage1, pRasterImage2, rectIntersect) {
    .Call('RasterAnalyser_Intersect', PACKAGE = 'RasterAnalyser', pRasterImage1, pRasterImage2, rectIntersect)
}

GetExtent <- function(pRasterImage, rectIntersect) {
    .Call('RasterAnalyser_GetExtent', PACKAGE = 'RasterAnalyser', pRasterImage, rectIntersect)
}

Clear <- function(pRasterImage) {
    invisible(.Call('RasterAnalyser_Clear', PACKAGE = 'RasterAnalyser', pRasterImage))
}

